@startuml
class TodoList {
    +id: int
    +owner: User
    getForUserId(int): TodoList[]
}

class TodoItem {
    +id: int
    +list: TodoList
    getForTodoListId(int): TodoItem[]
}

class User {
    +id: int
    +name: string
}

TodoList::owner -- User::id
TodoList::id -- TodoItem::list

@enduml