@startuml
(*) -->[git init] "Initialisér repo"
(*) -->[git clone] "Klone eksisterende repo"
"Initialisér repo" --> "Endre eller legg til innhold lokalt"
"Klone eksisterende repo" --> "Endre eller legg til innhold lokalt"
                          -->[git add/endre filer] "Endre eller legg til innhold lokalt"
"Endre eller legg til innhold lokalt" -->[git commit] "Commit endringene"
                                      --> "Endre eller legg til innhold lokalt"
"Commit endringene" -->[git pull] "Hent inn endringer fra hoved/annet repo "
                    -->[git push] "Last opp endringene til hoved/annet repo"
                    --> "Endre eller legg til innhold lokalt"
"Hent inn endringer fra hoved/annet repo" --> "Endre eller legg til innhold lokalt"
                                          -->[git pull] "Hent inn endringer fra hoved/annet repo"
"Last opp endringene til hoved/annet repo" --> (*)
@enduml