@startuml
"Kasse" --> "Kasse HW": Kunde vil betale med kort
"Kasse HW" -> Bankterminal: Ta betalt x kr
Bankterminal --> "Kasse HW": Betaling OK, her er data
"Kasse HW" -> "Kasse": Her er metadata om betalingen
"Kasse" -> "Kasse": Lagre metadata til Ordre
"Kasse" --> "Kasse HW": Skriv ut data
"Kasse HW" -> Printer: Skriv ut kvittering
Printer --> "Kasse HW": Print OK
"Kasse HW" --> "Kasse": Print OK
@enduml